/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import skyScene from '../assets/3d/sky.glb'

const Sky = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(skyScene)
  const { actions } = useAnimations(animations, group)
  return (
    <a.group ref={group} {...props} dispose={null}>
      <a.group name="Scene">
        <a.group name="Sphere_2" rotation={[-0.585, 0.233, -2.007]} scale={-90.65}>
          <mesh
            name="Object_17"
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials['Material.003']}
          />
          <mesh
            name="Object_18"
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials['Material.003']}
          />
        </a.group>
      </a.group>
    </a.group>
  )
}

export default Sky;